from enum import Enum
class Config(Enum):
    HUNGER_RATE = 2
    ADULT_AGE = 2
    PROD_RATIO = 10
    BIRTH_RATIO = 50
    IS_HOUSED_INC = 2
    HUNGRY_INC = 2
    DEATH_BORDER = 30
    HOMELESS_BIRTH_RATIO = 0.3
    HOUSE_COST = 10
    HOUSE_COST_MULT = 0.5
    HOUSE_MAX_RESIDENTS = 4
    WORKPLACE_MAX_RESIDENTS = 4
